# Microsoft Azure Build Pipeline Templates/Jobs
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
# https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/artifacts-overview?view=azure-devops

steps:

# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops
#- script: echo '##vso[task.setvariable variable=SourceVersionShort]$(Build.SourceVersion | cut -c 1-8)'

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install NodeJS'

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=azure-devops
- task: Npm@1
  inputs:
    command: install
  displayName: 'Install NPM Packages'

- script: npm run build:app
  displayName: 'Build (app)'

- script: npm run build:web
  displayName: 'Build (web)'

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/archive-files?view=azure-devops
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/build/latest' 
    includeRootFolder: false 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/web-$(Build.SourceVersion).zip' 
    replaceExistingArchive: true
  displayName: 'Copy Artifacts (web)'

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns
- task: CopyFiles@2
  inputs:
    contents: hakuneko-*@(.exe|.zip|.deb|.rpm|.dmg)
    sourceFolder: '$(Build.SourcesDirectory)/build'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: false
    overWrite: true
    flattenFolders: false
  displayName: 'Copy Artifacts (app)'

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: '$(Agent.OS)-$(Agent.OSArchitecture)_$(Build.BuildNumber)'
  displayName: 'Publish Artifacts'