# Microsoft Azure Build Pipeline Templates/Jobs
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: azure-pipelines-template.yml

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: azure-pipelines-template.yml

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: azure-pipelines-template.yml