# Microsoft Azure Build Pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema

# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops
pr: none
trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: azure-pipelines-ci-template.yml

- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: azure-pipelines-ci-template.yml

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: azure-pipelines-ci-template.yml