# Microsoft Azure Build Pipeline Templates/Jobs
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: install
  displayName: 'Install NPM Packages'

- script: |
    npm run test:app
  displayName: 'Tests'

- script: |
    npm run build:app
  displayName: 'Build'

- script: |
    echo 'Not Implemented'
  displayName: 'Deploy'