# Microsoft Azure Build Pipeline Templates/Jobs
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

steps:

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install NodeJS'

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=azure-devops
- task: Npm@1
  inputs:
    command: install
  displayName: 'Install NPM Packages'

-script: echo Export: ${{ parameters.export }}
  displayName: 'DEBUG'

- script: ${{ parameters.export }} npm run build:web
  displayName: 'Build (web)'

- script: ${{ parameters.export }} npm run test:app -- --reporter mocha-junit-reporter --reporter-options mochaFile=test-app.xml
  continueOnError: true
  displayName: 'Test (app)'

- script: ${{ parameters.export }} npm run test:web -- --reporter mocha-junit-reporter --reporter-options mochaFile=test-web.xml --renderer
  continueOnError: true
  displayName: 'Test (web)'

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-*.xml'
    mergeTestResults: true
    testRunTitle: 'TestResults_$(Agent.OS)'
    buildConfiguration: $(Agent.OS)
    buildPlatform: $(Agent.OSArchitecture)
  displayName: 'Publish Test Results'