# Microsoft Azure Build Pipeline
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: install
  displayName: 'Install NPM Packages'

- script: |
    npm run test:app
  displayName: 'Tests'

- script: |
    npm run build:app
  displayName: 'Build'

- script: |
    echo 'Not Implemented'
  displayName: 'Deploy'