# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: CI

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install NPM Packages
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build (web)
        run: npm run build:web
      - name: Test (app)
        run: npm run test:app
      - name: HELLO WORLD
        env:
          PROJECT: HakuNeko
        #working-directory: ${{ github.workspace }}
        run: |
          echo $PROJECT
          ls -la