name: CI

on:
  push:
    branches:
      - master

jobs:
  my-job:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        PROJECT: HakuNeko
      run: |
        ls
        echo $PROJECT