name: CI

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        env:
          PROJECT: HakuNeko
        working-directory: ${{ github.workspace }}
        run: |
          ls -la
          echo $PROJECT