name: CI

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
    #
    #- uses: actions/setup-node@v1
    #    with:
    #      node-version: 10.x
    #- name: Build
    #  env:
    #    PROJECT: HakuNeko
    #  working-directory: ${{ github.workspace }}
    #  run: |
    #    echo $PROJECT
    #    ls -la
